backend:
  name: github
  repo: mmillenaa/millena
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "research"
    label: "Teaching & Research"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Resumo (Aparece no Acordeão)", name: "description", widget: "text"}
      - {label: "Corpo do Texto", name: "body", widget: "markdown"}
